# Numpy - Numerical Python

- It stands for numerical python
- It is a library which consists of multi-dimensional array objects and a group of routines for processing those arrays.
- Numpy can be used to perform mathematical and logical operations on arrays.
- Numpy is imported using the following syntax: import numpy as np

# Numpy - Ndarray Object

- Important array object defined in Numpy is an n-dimensional array type called ndarray.
- It describes the group of items of the same type.
- Each item in the collection can be accessed using the zero-based index.
- Every item in the ndarray occupies the same amount of memory.
- Each element in an ndarray is an object of data-type object(called dtype).

### Examples

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
a = np.array([1.5,2.5,3.5,4.5])
print(a)

[1.5 2.5 3.5 4.5]


In [4]:
# more than one dimension
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [7]:
# dtype parameter
a = np.array([1,2,3], dtype=complex)
print(a)

a = np.array([1,2,3], dtype=str)
print(a)

[1.+0.j 2.+0.j 3.+0.j]
['1' '2' '3']


In [8]:
# using array-(scalar type
dt = np.dtype(np.int32)
print(dt)

int32


# Numpy - Array Attributes

- ndarray.shape - It returns a tuple containing array dimensions. It is used to resize the array

In [9]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)
