# Numpy - Numerical Python

- It stands for numerical python
- It is a library which consists of multi-dimensional array objects and a group of routines for processing those arrays.
- Numpy can be used to perform mathematical and logical operations on arrays.
- Numpy is imported using the following syntax: import numpy as np

# Numpy - Ndarray Object

- Important array object defined in Numpy is an n-dimensional array type called ndarray.
- It describes the group of items of the same type.
- Each item in the collection can be accessed using the zero-based index.
- Every item in the ndarray occupies the same amount of memory.
- Each element in an ndarray is an object of data-type object(called dtype).

### Examples

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
a = np.array([1.5,2.5,3.5,4.5])
print(a)

[1.5 2.5 3.5 4.5]


In [4]:
# more than one dimension
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [7]:
# dtype parameter
a = np.array([1,2,3], dtype=complex)
print(a)

a = np.array([1,2,3], dtype=str)
print(a)

[1.+0.j 2.+0.j 3.+0.j]
['1' '2' '3']


In [8]:
# using array-(scalar type
dt = np.dtype(np.int32)
print(dt)

int32


# Numpy - Array Attributes

- ndarray.shape - It returns a tuple containing array dimensions. It is used to resize the array

In [9]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


###### 
- ndarray.reshape - reshapes a array

In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

b = a.reshape(2,3)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


###### 
- ndarray.ndim - this array attribute returns the number of array dimensions

In [22]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


###### 
- ndarray.arange - creates a array of given range

In [6]:
import numpy as np
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [9]:
b = a.reshape(2,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


###### 
- numpy.itemsize - this attribute returns the length of each element of array in bytes

In [12]:
import numpy as np
x = np.array([1,2,3,4,5], dtype=np.int8)
print(x.itemsize)

1


In [10]:
# convert list to ndarray
import numpy as np
x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


# Trignometric Functions

- It has trignometric functions which return trignometric ratios for a given angle in radians.
- arcsin, arccos, and arctan return the inverse trignometric values of sin, cos, and tan of given angle.
- The result of these functions can be verified by numpy.degrees() function by converting radians to degrees.

### Example

In [15]:
import numpy as np
a = np.array([0,30,45,60,90])
print('Sine of different angles') 
print(np.sin(a*np.pi/180))
print()
print('Cosine values for angles in array')
print(np.cos(a*np.pi/180))
print()
print('Tangent values for given angles')
print(np.tan(a*np.pi/180))

Sine of different angles
[0.         0.5        0.70710678 0.8660254  1.        ]

Cosine values for angles in array
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Tangent values for given angles
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [21]:
import numpy as np
a = np.array([0,30,45,60,90])
print('Array containing sine values') 
sin = np.sin(a*np.pi/180)
print(sin)
print()
print('Compute sine inverse of angles. Returned values are in radians')
inv = np.arcsin(sin)
print(inv)
print()
print('Check result by converting to degrees')
print(np.degrees(inv))
print('\n\n')
print('Array containing cosine values')
cos = np.cos(a*np.pi/180)
print(cos)
print()
print('Inverse of cos')
inv = np.arccos(cos)
print(inv)
print()
print('Check result by converting to degrees')
print(np.degrees(inv))
print('\n\n')
print('Array containing tan values')
tan = np.tan(a*np.pi/180)
print(tan)
print()
print('Inverse of tan')
inv = np.arctan(tan)
print(inv)
print()
print('Check result by converting to degrees')
print(np.degrees(inv))

Array containing sine values
[0.         0.5        0.70710678 0.8660254  1.        ]

Compute sine inverse of angles. Returned values are in radians
[0.         0.52359878 0.78539816 1.04719755 1.57079633]

Check result by converting to degrees
[ 0. 30. 45. 60. 90.]



Array containing cosine values
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Inverse of cos
[0.         0.52359878 0.78539816 1.04719755 1.57079633]

Check result by converting to degrees
[ 0. 30. 45. 60. 90.]



Array containing tan values
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]

Inverse of tan
[0.         0.52359878 0.78539816 1.04719755 1.57079633]

Check result by converting to degrees
[ 0. 30. 45. 60. 90.]
